[package]
name = "vectorcxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.73"
# without disabling default features, cargo will complain `libz-sys` feature is required but vector doesn't have it
# for release, use "vector = { git = "https://github.com/yanhuangdata/vector.git", branch = "feature/vector-lib" }"
# for local repo test, use "vector = { path = "{path_to_local_vector_repo}" }"
vector = { path = "vector", features = [
    "api",
    "api-client",
    "disk-buffer",
    "enrichment-tables",
    "rdkafka-plain",
    "sinks",
    "sources",
    "sources-dnstap",
    "transforms",
    "unix",
    "vrl-cli",
    "openssl",
    "vendor-sasl",
], default-features = false }
tempfile = "3.2.0"
futures = "0.3.17"
tokio = { version = "1.13.0", features = ["test-util"] }
tokio-test = "0.4.2"
rdkafka = { version = "0.27.0", default-features = false, features = ["tokio", "libz", "ssl", "zstd", "dynamic-linking"]}
concurrent-queue = "1.2.4"

[build]
jobs = 12

[build-dependencies]
cxx-build = "1.0.73"

[lib]
crate-type = ["staticlib"]
# below config options make the the build of dynamic lib available
#crate-type = ["cdylib"]

#[profile.dev]
#rpath = true