name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: probrian35/vectorcxx_dev:latest
      env:
        NODE_ENV: development
      ports:
        - 80
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Tracing
        env:
          RUST_TOOLCHAIN_VERSION: 1.64.0
        run: 
          rustup show
          rustup toolchain list
          rustup default
          rustc --version
          rustup --version
      # - name: Update submodule
      #   run: git submodule update --init --recursive
      # - name: Build
      #   env:
      #     RUST_TOOLCHAIN_VERSION: 1.64.0
      #   run: VECTORCXX_VCPKG_MANIFEST_DIR=$PWD/ci/dev_image just cmake && just build
      # - name: Test
      #   run: cd build-cmake-debug-linux && ctest